account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path("", views.AccountView.as_view(), name="account"),
    path("edit/", views.EditView.as_view(), name="edit"),
    path("password/change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.SearchView.as_view(), name="list"),
    path("tags/", views.TagsView.as_view(), name="tags"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:pk>/", views.PostView.as_view(), name="post"),
    path("<int:pk>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DeleteView.as_view(), name="delete"),
    path("render/", views.RenderMarkdown.as_view(), name="render"),
    path("upload/", views.UploadView.as_view(), name="upload"),
    path("upload/<int:pk>/delete/", views.UploadDeleteView.as_view(), name="upload-delete"),
]

common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("account/", include("account.urls", namespace="account")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("boxes/", include("boxes.urls", namespace="boxes")),
    path("about_me/", TemplateView.as_view(template_name="about.html"), name="about_me"),
    path("login/", RedirectView.as_view(url="/account/login/", permanent=False)),
    path("logout/", RedirectView.as_view(url="/account/login/", permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/templates/includes/messages.html
{% if messages %}
<div class="fixed-top">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true"><i class="fas fa-times fa-fw"></i></span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

common/templates/includes/sidebar.html
{% load static %}
<button type="button" id="chev" class="btn sidenav-button" onclick="toggleSidebar()">
  <i class="fas fa-chevron-right"></i>
</button>
<div class="sidenav">
    <a href="{% url 'index' %}"><img class="img-fluid d-block mx-auto" src="{% static 'img/logo.png' %}"></a>
    <div class="sidenav-controls" style="flex:1">
        {% if date %}
        <time class="d-block text-center">{{ date }}</time>
        <div>
            <hr>
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <a href="{% url 'blog:create' %}"><i class="fas fa-pencil-alt fa-fw mr-2"></i>Create Post</a>
        <div>
            <hr>
        </div>
        {% endif %}
        <a href="{% url 'about_me' %}"><i class="fas fa-address-card fa-fw mr-2"></i>About me</a>
        <div>
            <hr>
        </div>
        <a href="{% url 'blog:list' %}"><i class="fas fa-blog mr-2"></i>Blog Posts</a>
        <a href="{% url 'blog:tags' %}"><i class="fas fa-tags mr-2"></i>Blog Tags</a>
        <div>
            <hr>
        </div>
        {% for year in years %}
        <a href="{% url 'blog:list' %}?year={{ year }}"><i class="fas fa-calendar-day mr-2"></i>{{ year }}</a>
        {% endfor %}
        <div>
            <hr>
        </div>
        {% if user.is_authenticated %}
        <a href="{% url 'account:account' %}"><i class="fas fa-user fa-fw mr-2"></i>My Account</a>
        <a href="{% url 'account:logout' %}"><i class="fas fa-sign-out-alt fa-fw mr-2"></i>Log out</a>
        {% else %}
        <a href="{% url 'account:login' %}"><i class="fas fa-sign-in-alt fa-fw mr-2"></i>Log in</a>
        {% endif %}
    </div>
    <a class="link-unstyled" href="https://novawebdevelopment.org/">
        <p class="text-center">COPYRIGHT © 2020<br>NOVA WEB DEVELOPMENT</p>
    </a>
</div>