blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.SearchView.as_view(), name="list"),
    path("tags/", views.TagsView.as_view(), name="tags"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:pk>/", views.PostView.as_view(), name="post"),
    path("<int:pk>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DeleteView.as_view(), name="delete"),
    path("render/", views.RenderMarkdown.as_view(), name="render"),
    path("upload/", views.UploadView.as_view(), name="upload"),
    path("upload/<int:pk>/delete/", views.UploadDeleteView.as_view(), name="upload-delete"),
]

common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("account/", include("account.urls", namespace="account")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("boxes/", include("boxes.urls", namespace="boxes")),
    path("about_me/", TemplateView.as_view(template_name="about.html"), name="about_me"),
    path("login/", RedirectView.as_view(url="/account/login/", permanent=False)),
    path("logout/", RedirectView.as_view(url="/account/login/", permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def get_html_count(self):
        return self.posts.count() * 6 + 12


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = models.ManyToManyField(Tag, related_name="posts", blank=True)
    created_at = models.DateField(help_text="Must be formatted as YYYY-MM-DD")
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_at"]


class Upload(models.Model):
    file = models.FileField(upload_to="uploads/")
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

blog/forms.py
from datetime import date
from django import forms
from blog.models import Post, Upload


class PostForm(forms.ModelForm):
    tags_list = forms.CharField(label="Tags", required=False)

    class Meta:
        model = Post
        exclude = ("tags",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["created_at"].initial = date.today()


class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = "__all__"

blog/views.py
from datetime import date
from django.views import View
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, reverse
from django.forms.models import modelform_factory
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from next_prev import next_in_order, prev_in_order
from blog.forms import PostForm, UploadForm
from blog.models import Post, Tag, Upload


class SearchView(View):
    def get(self, request):
        tag = request.GET.get("tag", None)
        year = request.GET.get("year", None)
        if request.user.is_authenticated:
            if tag:
                tag_obj = get_object_or_404(Tag, name=tag)
                posts = tag_obj.posts.all().distinct()
            elif year and year.isnumeric():
                posts = Post.objects.filter(created_at__year=year)
            else:
                search = request.GET.get("search", "")
                posts = Post.objects.filter(
                    Q(title__contains=search) | Q(tags__name__contains=search) | Q(content__contains=search)
                ).distinct()
            return render(request=request, template_name="blog/search.html", context={"posts": posts})
        else:
            if tag:
                tag_obj = get_object_or_404(Tag, name=tag)
                posts = tag_obj.posts.filter(is_published=True).distinct()
            elif year and year.isnumeric():
                posts = Post.objects.filter(created_at__year=year).filter(is_published=True)
            else:
                search = request.GET.get("search", "")
                posts = (
                    Post.objects.filter(
                        Q(title__contains=search) | Q(tags__name__contains=search) | Q(content__contains=search)
                    )
                    .filter(is_published=True)
                    .distinct()
                )
            return render(request=request, template_name="blog/search.html", context={"posts": posts})


class TagsView(View):
    def get(self, request):
        tags = Tag.objects.filter(posts__isnull=False).distinct()
        return render(request=request, template_name="blog/tags.html", context={"tags": tags})


class CreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = PostForm()
        return render(request=request, template_name="blog/create.html", context={"form": form})

    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            for tag_name in form.cleaned_data["tags_list"].split(","):
                tag = Tag.objects.get_or_create(name=tag_name)
                post.tags.add(tag[0].pk)
            post.save()
            messages.success(request, "You have successfully created a new blog post.")
            return HttpResponseRedirect(reverse("index"))
        return render(request=request, template_name="blog/create.html", context={"form": form})


class PostView(View):
    def get(self, request, pk=None):
        post = get_object_or_404(Post, pk=pk)
        return render(
            request=request,
            template_name="blog/post.html",
            context={"post": post, "prev": prev_in_order(post), "next": next_in_order(post), "date": date.today()},
        )


class EditView(LoginRequiredMixin, View):
    def get(self, request, pk=None):
        post = get_object_or_404(Post, pk=pk)
        tags_list = ",".join([tag.name for tag in set(post.tags.all())])
        form = PostForm(instance=post, initial={"tags_list": tags_list})
        return render(request=request, template_name="blog/edit.html", context={"form": form})

    def post(self, request, pk=None):
        post = get_object_or_404(Post, pk=pk)
        tags_list = ",".join([tag.name for tag in set(post.tags.all())])
        form = PostForm(request.POST, instance=get_object_or_404(Post, pk=pk), initial={"tags_list": tags_list})
        if form.is_valid():
            post = form.save()
            post.tags.clear()
            for tag_name in form.cleaned_data["tags_list"].split(","):
                tag = Tag.objects.get_or_create(name=tag_name)
                post.tags.add(tag[0].pk)
            post.save()
            messages.success(request, "You have successfully edited a blog post.")
            return HttpResponseRedirect(reverse("index"))
        return render(request=request, template_name="blog/edit.html", context={"form": form})


class DeleteView(LoginRequiredMixin, View):
    def get(self, request, pk=None):
        return render(request=request, template_name="blog/delete.html")

    def post(self, request, pk=None):
        get_object_or_404(Post, pk=pk).delete()
        messages.success(request, "You have successfully deleted a blog post.")
        return HttpResponseRedirect(reverse("index"))


@method_decorator(csrf_exempt, name="dispatch")
class RenderMarkdown(LoginRequiredMixin, View):
    def post(self, request):
        return render(
            request=request, template_name="blog/render.html", context={"content": request.POST.get("content", "")}
        )


class UploadView(LoginRequiredMixin, View):
    def get(self, request):
        uploads = Upload.objects.all()
        return render(self.request, "blog/upload_list.html", {"uploads": uploads})

    def post(self, request):
        form = UploadForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            upload = form.save()
            data = {"is_valid": True, "name": upload.file.name, "url": upload.file.url}
        else:
            data = {"is_valid": False}
        return JsonResponse(data)


class UploadDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk=None):
        get_object_or_404(Upload, pk=pk)
        return render(request=request, template_name="blog/upload_delete.html")

    def post(self, request, pk=None):
        get_object_or_404(Upload, pk=pk).delete()
        messages.success(request, "You have successfully deleted a file.")
        return HttpResponseRedirect(reverse("blog:upload"))

blog/templates/blog/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create Post{% endblock title %}
{% block subtitle %}The new blog post will appear at the top of the list.{% endblock subtitle %}
\
{% block content %}
<link rel="stylesheet" href="{% static 'css/amsify.suggestags.css' %}">
<script src="{% static 'js/jquery.amsify.suggestags.js' %}"></script>

<form novalidate method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
        <div class="mt-3" id="preview" style="border: 4px double #ced4da; padding: 1rem;"></div>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-form">Submit</button>
        <a class="btn btn-link" href="https://docutils.sourceforge.io/docs/user/rst/quickref.html" target="_blank">reStructuredText Help</a>
    </div>
</form>
{% endblock content %}

blog/templates/blog/delete.html
{% extends "base.html" %}

{% block title %}Delete Post{% endblock title %}
{% block subtitle %}The post will be deleted forever (not archived).{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    <div class="form-group">
        Are you sure you want to proceed?
        <br>
        This action is <span class="text-danger">irreversible</span>.
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-danger btn-form">Submit</button>
    </div>
</form>
{% endblock content %}

blog/templates/blog/edit.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Edit Post{% endblock title %}
{% block subtitle %}Editing the post will keep the original creation date.{% endblock subtitle %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/amsify.suggestags.css' %}">
<script src="{% static 'js/jquery.amsify.suggestags.js' %}"></script>

<form novalidate method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
        <div class="mt-3" id="preview" style="border: 4px double #ced4da; padding: 1rem;"></div>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-warning btn-form">Submit</button>
        <a class="btn btn-link" href="https://docutils.sourceforge.io/docs/user/rst/quickref.html" target="_blank">reStructuredText Help</a>
    </div>
</form>
{% endblock content %}

blog/templates/blog/post.html
{% extends "base.html" %}
{% load restruct %}

{% block title %}
{{ post.title }}
{% if user.is_authenticated %}
<a class="btn btn-warning" href="{% url 'blog:edit' pk=post.pk %}"><i class="fas fa-pen"></i></a>
<a class="btn btn-danger" href="{% url 'blog:delete' pk=post.pk %}"><i class="fas fa-trash"></i></a>
<a class="btn btn-primary" href="#" onclick="javascript:genPDF()"><i class="fas fa-file-pdf fa-fw"></i></a>
{% endif %}

<h2>{{ post.created_at }}</h2>

{% endblock title %}

{% block extra_head %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
{% endblock extra_head %}

{% block content %}
<div class="container-fluid no-gutters">
    <div class="row">
        <div class="col-12" id="pdf">
            {{ post.content|restruct }}
        </div>
    </div>
    <div class="row justify-content-between">
        {% if prev %}
        <a class="btn btn-dark" href="{% url 'blog:post' pk=prev.pk %}"><i class="fas fa-chevron-left fa-fw"></i></a>
        {% else %}
        <a class="btn btn-dark disabled" href="#"><i class="fas fa-chevron-left fa-fw"></i></a>
        {% endif %}
        {% if next %}
        <a class="btn btn-dark" href="{% url 'blog:post' pk=next.pk %}"><i class="fas fa-chevron-right fa-fw"></i></a>
        {% else %}
        <a class="btn btn-dark disabled" href="#"><i class="fas fa-chevron-right fa-fw"></i></a>
        {% endif %}
    </div>
</div>
{% endblock content %}

blog/templates/blog/render.html
{% load restruct %}
{{ content|restruct }}

blog/templates/blog/search.html
{% extends "base.html" %}

{% block title %}Blog Posts{% endblock title %}
{% block subtitle %}Welcome! These are all the blog posts.{% endblock subtitle %}

{% block content %}
<div class="row">
    <div class="col">
        <form type="get" action="." style="margin: 0">
            <div class="input-group mb-1">
                <input autofocus class="form-control" id="search" type="text" name="search" placeholder="Search">
                <div class="input-group-append">
                    <button class="btn btn-primary" id="search_submit" type="submit"><i class="fas fa-search fa-fw"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>
{% for post in posts %}
<div>
    <hr>
    <div class="row">
        <div class="col-9">
            <h5><a class="post-link" href="{% url 'blog:post' pk=post.pk %}">{{ post.title }}</a></h5>
            {% for tag in post.tags.all %}
            <a class="badge badge-secondary font-weight-normal" href="{% url 'index' %}?tag={{ tag.name }}">{{ tag.name }}</a>
            {% endfor %}
        </div>
        <div class="col-3">
            <time>{{ post.created_at }}</time>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}

blog/templates/blog/tags.html
{% extends "base.html" %}

{% block title %}Blog Tags{% endblock title %}
{% block subtitle %}These are all the tags that are being used in blog posts.{% endblock subtitle %}

{% block content %}
{% for tag in tags %}
<a class="font-weight-normal" style="padding: 1.5rem 1rem; font-size: {{ tag.get_html_count }}px" href="{% url 'index' %}?tag={{ tag.name }}">{{ tag.name }}</a>
{% endfor %}
{% endblock content %}

blog/templates/blog/upload_delete.html
{% extends "base.html" %}

{% block title %}Delete Upload{% endblock title %}
{% block subtitle %}The upload will be deleted forever.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    <div class="form-group">
        Are you sure you want to proceed?
        <br>
        This action is <span class="text-danger">irreversible</span>.
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-danger btn-form">Submit</button>
    </div>
</form>
{% endblock content %}

blog/templates/blog/upload_list.html
{% extends "base.html" %}

{% block title %}Upload Files{% endblock title %}

{% block content %}
<style>
    .my-custom-scrollbar {
        position: relative;
        height: 80vh;
        overflow: auto;
    }
</style>
<script src="/static/js/jquery.upload.js"></script>
<script src="/static/js/jquery.iframe.js"></script>
<script src="/static/js/jquery.fileupload.js"></script>
<script>
    $(function () {
        /* 1. OPEN THE FILE EXPLORER WINDOW */
        $(".js-upload-photos").click(function () {
            $("#fileupload").click();
        });

        /* 2. INITIALIZE THE FILE UPLOAD COMPONENT */
        $("#fileupload").fileupload({
            dataType: 'json',
            done: function (e, data) {  /* 3. PROCESS THE RESPONSE FROM THE SERVER */
                if (data.result.is_valid) {
                    $("#gallery tbody").prepend(
                        "<tr><td><a href='" + data.result.url + "'>" + data.result.name + "</a></td></tr>"
                    )
                    window.location.reload();
                }
            }
        });
    });
</script>
<div class="card-body my-custom-scrollbar">
    <button type="button" class="btn btn-primary js-upload-photos">
        <span class="glyphicon glyphicon-cloud-upload"></span> Upload Files
    </button>
    <input id="fileupload" type="file" name="file" multiple style="display: none;" data-url="{% url 'blog:upload' %}"
        data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
    <table id="gallery" class="table table-striped nowrap" style="width: 100%;">
        <tbody>
            {% for upload in uploads %}
            <tr>
                <td><a href="{{ upload.file.url }}">{{ upload.file.name }}</a></td>
                <td>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}